CREATE DATABASE LOJA;
USE LOJA;

CREATE TABLE CLIENTE(
	IDCLIENTE INT AUTO_INCREMENT PRIMARY KEY,
	NOME VARCHAR(30) NOT NULL,
	EMAIL VARCHAR(50) UNIQUE,
	CPF VARCHAR(15) UNIQUE,
	SEXO ENUM ('M','F') NOT NULL
);

CREATE TABLE TELEFONE(
	IDTELEFONE INT PRIMARY KEY AUTO_INCREMENT,
	TIPO ENUM('COM','RES','CEL'),
	NUMERO VARCHAR(10),
	ID_CLIENTE INT,
	FOREIGN KEY(ID_CLIENTE)
	REFERENCES CLIENTE(IDCLIENTE)
);

CREATE TABLE ENDERECO(
	IDENDERECO INT AUTO_INCREMENT PRIMARY KEY,
	RUA VARCHAR(30) NOT NULL,
	BAIRRO VARCHAR(30) NOT NULL,
	CIDADE VARCHAR(30) NOT NULL,
	ESTADO CHAR(2) NOT NULL,
	ID_CLIENTE INT UNIQUE,
	FOREIGN KEY (ID_CLIENTE)
	REFERENCES CLIENTE (IDCLIENTE)
);

INSERT INTO CLIENTE VALUES(NULL,'JOAO','JOAO@IG.COM','98547-6','M');
INSERT INTO CLIENTE VALUES(NULL,'CARLOS','CARLOS@TERRA.COM','86664-7','M');
INSERT INTO CLIENTE VALUES(NULL,'ANA','ANA@GLOBO.COM','75658-5','F');

INSERT INTO CLIENTE VALUES(NULL,'CLARA',NULL,'99754-7','F');
INSERT INTO CLIENTE VALUES(NULL,'CELIA','JOAO@TERRA.COM','77558-5','F');


INSERT INTO CLIENTE VALUES (NULL,'ANTONIO',NULL,'78558-6','M');
INSERT INTO CLIENTE VALUES (NULL,'JOAO',NULL,'86695-6','M');


INSERT INTO ENDERECO VALUES(NULL,'RUA A','CENTRO','B. HORIZONTE','MG',7);
INSERT INTO ENDERECO VALUES(NULL,'RUA B','CENTRO','RIO DE JANEIRO','RJ',1);
INSERT INTO ENDERECO VALUES(NULL,'RUA C','JARDINS','SÃO PAULO','SP',3);
INSERT INTO ENDERECO VALUES(NULL,'RUA B','ESTACIO','RIO DE JANEIRO','RJ',8);
INSERT INTO ENDERECO VALUES(NULL,'RUA Z','CRUZEIRO','B. HORIZONTE','MG',2);
INSERT INTO ENDERECO VALUES(NULL,'RUA X','FLAMENGO','RIO DE JANEIRO','RJ',5);
INSERT INTO ENDERECO VALUES(NULL,'RUA X','VILA MEDEIROS','sAO PAULO','SP',4);
INSERT INTO ENDERECO VALUES(NULL,'RUA X','NITEROI','RIO DE JANEIRO','RJ',6);

DELETE FROM TELEFONE WHERE ID_CLIENTE = 6;

INSERT INTO TELEFONE VALUES(NULL,'COM','99587545',1);
INSERT INTO TELEFONE VALUES(NULL,'COM','71218326',2);
INSERT INTO TELEFONE VALUES(NULL,'CEL','71218326',2);
INSERT INTO TELEFONE VALUES(NULL,'CEL','71218326',1);
INSERT INTO TELEFONE VALUES(NULL,'COM','71218326',5);
INSERT INTO TELEFONE VALUES(NULL,'COM','29824271',6);
INSERT INTO TELEFONE VALUES(NULL,'CEL','71218326',6);
INSERT INTO TELEFONE VALUES(NULL,'CEL','71218326',8);
INSERT INTO TELEFONE VALUES(NULL,'RES','71218326',8);
INSERT INTO TELEFONE VALUES(NULL,'CEL','71218326',5);
INSERT INTO TELEFONE VALUES(NULL,'CEL','71218326',6);
INSERT INTO TELEFONE VALUES(NULL,'RES','71218326',5);

SELECT * FROM CLIENTE ;
SELECT * FROM TELEFONE ;
SELECT * FROM ENDERECO ;

SELECT NOME, NOW() AS "DATA" FROM CLIENTE;

SELECT NOME, SEXO FROM CLIENTE WHERE SEXO = 'M';

UPDATE CLIENTE
SET SEXO = 'F' WHERE IDCLIENTE = 5;



SELECT NOME, SEXO FROM CLIENTE WHERE IDCLIENTE = 5;


SELECT NOME, SEXO, BAIRRO, CIDADE, NOW() AS 'DATA'
FROM CLIENTE, ENDERECO
WHERE IDCLIENTE = ID_CLIENTE;

UPDATE ENDERECO
SET ESTADO = 'RJ' 
WHERE ID_CLIENTE = 7;

SELECT NOME, SEXO, BAIRRO, CIDADE
FROM CLIENTE
INNER JOIN ENDERECO
ON IDCLIENTE = ID_CLIENTE
WHERE BAIRRO = 'VILA MEDEIROS';


SELECT C.NOME, C.SEXO, 
	   E.BAIRRO, E.CIDADE, 
	   T.TIPO, T.NUMERO
FROM CLIENTE C
INNER JOIN ENDERECO E
ON C.IDCLIENTE = E.ID_CLIENTE
INNER JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE
WHERE SEXO = 'M';

SELECT C.NOME, C.SEXO, 
	   E.BAIRRO, E.CIDADE, 
	   T.TIPO, T.NUMERO
FROM CLIENTE C
INNER JOIN ENDERECO E
ON C.IDCLIENTE = E.ID_CLIENTE
INNER JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE
WHERE SEXO = 'F';



UPDATE CLIENTE 
SET EMAIL = 'ANTONIO@GMAIL.COM'
WHERE IDCLIENTE = 6;

UPDATE CLIENTE 
SET EMAIL = 'CLARA@GMAIL.COM'
WHERE IDCLIENTE = 4;




