/* Auto relacionamento */ 

CREATE DATABASE AULA44;
USE AULA44



CREATE TABLE CURSOS(
	IDCURSO INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30),
	HORAS INT,
	VALOR FLOAT(10,2),
	ID_PREREQ INT 
);

ALTER TABLE CURSOS ADD 
CONSTRAINT FK_PREREQ
FOREIGN KEY (ID_PREREQ) REFERENCES CURSOS (IDCURSO);

INSERT INTO CURSOS VALUES(NULL,'BD RELACIONAL',20,400.0,NULL);
INSERT INTO CURSOS VALUES(NULL,'BUSINESS INTELLIGENCE',40,800.0,1);
INSERT INTO CURSOS VALUES(NULL,'RELATORIOS AVANCADOS',20,600.0,2);
INSERT INTO CURSOS VALUES(NULL,'LOGICA DE PROGRAMAÇÃO',20,400.0,NULL);
INSERT INTO CURSOS VALUES(NULL,'RUBY',30,500.0,4);

SELECT C.NOME AS 'CURSO', 
	   C.VALOR AS 'VALOR', 
	   C.HORAS AS 'CARGA HORARIA', 
	   IFNULL(P.NOME, '---') AS PRERQ
FROM CURSOS C
LEFT JOIN CURSOS P
ON P.IDCURSO = C.ID_PREREQ;