/* CURSORES */ 

CREATE DATABASE CURSORES;
USE CURSORES;

CREATE TABLE VENDEDORES(
	IDVENDEDOR INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(50),
	JAN INT,
	FEV INT,
	MAR INT
);

INSERT INTO VENDEDORES VALUES(NULL,'CAUE',32432,21345,21645);
INSERT INTO VENDEDORES VALUES(NULL,'CLARA',45698,452315,121646);
INSERT INTO VENDEDORES VALUES(NULL,'JOAO',325422,242334,3161152);
INSERT INTO VENDEDORES VALUES(NULL,'LILIAN',56312,51213,213452);
INSERT INTO VENDEDORES VALUES(NULL,'ANTONIO',64585,25430,121643);
INSERT INTO VENDEDORES VALUES(NULL,'GLOARIA',25756,24547,313512);

SELECT BOME, (JAN+FEV+MAR) AS TOTAL FROM VENDEDORES;
SELECT NOME, (JAN++FEV+MAR) AS TOTAL, (JAN+FEV+MAR)/3 AS MEDIA FROM VENDEDORES;

CREATE TABLE VEND_TOTAL(
	NOME VARCHAR(50),
	JAN INT,
	FEV INT,
	MAR INT,
	TOTAL INT,
	MEDIA INT 
);

DELIMITER $

CREATE PROCEDURE INSEREDADOS()
BEGIN 
	DECLARE FIM INT DEFAULT 0;
	DECLARE VAR1, VAR2, VAR3, VTOTAL, VMEDIA INT;
	DECLARE VNOME VARCHAR(50);
	
	DECLARE REG CURSOR FOR(
		SELECT NOME, JAN, FEV, MAR FROM VENDEDORES
	);
	
	DECLARE CONTINUE HANDLER FOR NOT FOUND SET FIM = 1;
	
	OPEN REG;
	
	REPEAT 
	
		FETCH REG INTO VNOME, VAR1, VAR2, VAR3;
		IF NOT FIM THEN 
			SET VTOTAL = VAR1 + VAR2 + VAR3;
			SET VMEDIA = VTOTAL/3;
		
			INSERT INTO VEND_TOTAL VALUES(VNOME,VAR1,VAR2,VAR3,VTOTAL,VMEDIA);
		END IF;	
	UNTIL FIM END REPEAT;
	
	CLOSE REG;
END
$



SELECT * FROM VENDEDORES;

CALL INSEREDADOS();
SELECT * FROM VEND_TOTAL;















