/* order by */

SELECT C.NOME, C.SEXO, C.CPF, E.CIDADE
FROM CLIENTE C
INNER JOIN ENDERECO E
ON C.IDCLIENTE = E.ID_CLIENTE
ORDER BY NOME, CPF ASC;

SELECT C.NOME, C.SEXO, C.CPF, E.CIDADE
FROM CLIENTE C
INNER JOIN ENDERECO E
ON C.IDCLIENTE = E.ID_CLIENTE
ORDER BY NOME, CPF DESC;

DELETE FROM CLIENTE
WHERE CPF = '86695-6';

DELETE FROM ENDERECO
WHERE ID_CLIENTE = 7;

DELETE FROM TELEFONE 
WHERE ID_CLIENTE = 7;